* Burgess' Note Collection
This is my personal note collection, including some piecemeal notes or code that
not enough to write a blog. The note's document format I am using includes:
- org-mode
- Markdown
- Jupyter Notebook
So if you want to check out to your local, you need do some preparation work to
have better display.
** Preparations
*** org-mode
You need install Emacs.
*** Jupyter
You need install some Jupyter kernel for program language that I use.
You can import a base anaconda3 environment: ~conda env create -f environment.yml~
**** C++
[[https://github.com/QuantStack/xeus-cling][xeus-cling]]
**** Rust
[[https://github.com/google/evcxr][evcxr]]
**** SQL
I choose to use MYSQL, it correctly configured in my anaconda3 environment.
After import environment, you need create a database named /note/. When you want
to run SQL code, maybe you need modify user name and password.
** Introduction
*** Leetcode file name rule
I use this format to name a leetcode note: ~id-question.lang.format~
- ~id~ mean leetcode question numbering
- ~question~ mean leetcode question title
- ~lang~ mean the program language type that I use to solve question
- ~format~ note document format
